import os
import io
import json
import base64
import google.generativeai as genai
from dotenv import load_dotenv
from PIL import Image
from typing import Any, Dict, List, Optional
from db import ReceiptDB
from dependencies import get_db
from fastapi import Depends
from schemas import ReceiptCreate, ReceiptImage
from sqlalchemy.orm import Session
from fastapi import HTTPException, UploadFile, File

load_dotenv()

system_instruction = """
You are an advanced AI assistant specializing in high-accuracy receipt data extraction, itemization, and categorization.

Your sole function is to analyze a receipt image and return a single, structured JSON object. **Do not** include any text, markdown formatting, or explanations outside of the JSON itself.

You MUST adhere to the following JSON schema and logic:

{
  ""id"": ""string"", // Use a placeholder like ""receipt-001""
  ""store"": ""string"", // The name of the merchant/store.
  ""total"": ""float"", // The final total amount paid.
  ""date"": ""YYYY-MM-DD"", // The transaction date.
  ""items"": ""integer"", // The total count of unique items in the `itemsList`.
  ""status"": ""success"", // Use ""success"" if data is extracted.
  ""categories"": [
    {
      ""name"": ""string"", // The category name.
      ""amount"": ""float"", // The sum of all item prices in this category.
      ""percentage"": ""integer"" // The percentage of the total, rounded to the nearest integer.
    }
  ],
  ""itemsList"": [
    {
      ""name"": ""string"",
      ""price"": ""float"", // The total price for this line item (unit_price * quantity).
      ""quantity"": ""integer"", // If not specified, assume 1.
      ""category"": ""string"" // The assigned category for this item.
    }
  ]
}

**Key Instructions & Logic:**

1.  **Categorization**: For each item in `itemsList`, you MUST assign a `category` from the following list based on your best judgment: **Groceries**, **Household**, **Personal Care**, **Electronics**, **Clothing**, **Dining**, **Entertainment**, **Other**.
2.  **Calculations**:
    * The `""items""` field must be the total count of objects in the `itemsList` array.
    * The `""categories""` array must be generated by grouping the items from `itemsList` by their assigned category.
    * For each category group, you must calculate the total `amount` by summing the `price` of all items in that group.
    * You must also calculate the `percentage` for each category: (`category.amount` / `total`) * 100, rounded to the nearest whole number.
3.  **Data Formatting**: All monetary values must be numbers (float), not strings with currency symbols. Dates must be in `YYYY-MM-DD` format.
4.  **Completeness**: Ensure all fields are populated. If a value cannot be determined, use `null`.
"""

def create_receipt(receipt_base64: ReceiptImage, db: Session) -> ReceiptDB:
    """
    Creates a new receipt record in the database

    Args:
        receipt: base64 image
        db: db session dependency


    Returns: Newly created receipt record
    """
    api_key=os.getenv("GOOGLE_API_KEY")

    if not api_key:
        raise HTTPException(status_code=500, detail="Google API key not working")
    genai.configure(api_key=api_key)

    try:
        image_bytes = base64.b64decode(receipt_base64.image_base64)
        with Image.open(io.BytesIO(image_bytes)) as receipt_img:
            mime_type = f"image/{receipt_img.format.lower()}"
   
    except Exception as r:
        raise HTTPException(status_code=400, detail=f"Input not in base64 format")
    
    try:
        model = genai.GenerativeModel(
            model_name="gemini-2.5-flash",
            generation_config={"response_mime_type": "application/json"},
            system_instruction=system_instruction
        )

        image_part = {
            "mime_type": mime_type,
            "data": receipt_base64.image_base64
        }

        prompt = [
            "Analyze the provided receipt image and generate the JSON output according to the instructions",
            image_part
        ]

        response = model.generate_content(prompt)

        receipt_json = json.loads(response.text)

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to process receipt with Gemini: {e}")
    
    try:
        extracted_data = ReceiptCreate(
            store=receipt_json.get("store"),
            total= receipt_json.get("total"),
            date=receipt_json.get("date"),
            items=receipt_json.get("items"),
            itemsList=receipt_json.get("itemsList", []),
            categories=receipt_json.get("categories", [])
        )

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"The extracted data was not in ReceiptCreate format, {e}")         

    try:
        items_list_as_dicts = [item.model_dump() for item in extracted_data.itemsList]
        categories_as_dicts = [cat.model_dump() for cat in extracted_data.categories]

        db_receipt = ReceiptDB(
            store=extracted_data.store,
            total=extracted_data.total,
            date=extracted_data.date,
            items=extracted_data.items,
            status="success",    
            itemsList=json.dumps(items_list_as_dicts),
            categories=json.dumps(categories_as_dicts)
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to map data to ReceiptDB: {e}")
    
    db.add(db_receipt)
    db.commit()
    db.refresh(db_receipt)
    return db_receipt


def get_all_receipts(db: Session) -> List[Dict[str, Any]]:
    """
    Retrieves all receipt records in the database

    Args:
        db: database session dependency

    Returns:
        List of all receipt records in the database, each conforming
        to ReceiptResponse schema
    """
    return db.query(ReceiptDB).all()


def get_receipt(receipt_id: int, db: Session) -> Optional[Dict[str, Any]]:
    """
    Retrieves a receipt record given a {receipt_id}

    Args:
        receipt_id: int unique id of the receipt record to be retrieved
        db

    Returns: The receipt record with that unique id
    """

    return db.query(ReceiptDB).filter(ReceiptDB.id == receipt_id).first()
